// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztkmjjagusdhshuxcuxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0a21qamFndXNkaHNodXhjdXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTA4OTksImV4cCI6MjA1ODY2Njg5OX0.5pJY6kteHF2cTNaqi0d3QnPXgVEMv4DgQ7kmZnuy_Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});